// Do not edit by hand, this file was automatically generated by ./gen_symbols.rb

#include "symbols/environment.hpp"
#include "symbols/namespace.hpp"
#include "symbols/symbol.hpp"

void init_environment_rel(EnvironmentPtr env)
{
  {
    NamespacePtr ns = env->add_namespace("playstation");
    env->add_namespace_alias("ps", ns);
    env->add_namespace_alias("psx", ns);
    env->add_namespace_alias("ps2", ns);
    env->add_namespace_alias("ps3", ns);
    env->add_namespace_alias("playstation2", ns);
    env->add_namespace_alias("playstation3", ns);
  }
  {
    NamespacePtr ns = env->add_namespace("evdev");
    env->add_namespace_alias("ev", ns);
    {
      SymbolPtr sym = ns->add_symbol("REL_MISC");
      ns->add_alias("KEY_#9", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_Z");
      ns->add_alias("KEY_#2", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_WHEEL");
      ns->add_alias("KEY_#8", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_DIAL");
      ns->add_alias("KEY_#7", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_HWHEEL");
      ns->add_alias("KEY_#6", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_RX");
      ns->add_alias("KEY_#3", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_RY");
      ns->add_alias("KEY_#4", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_RZ");
      ns->add_alias("KEY_#5", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_X");
      ns->add_alias("KEY_#0", sym);
    }
    {
      SymbolPtr sym = ns->add_symbol("REL_Y");
      ns->add_alias("KEY_#1", sym);
    }
  }
  {
    NamespacePtr ns = env->add_namespace("xbox");
    env->add_namespace_alias("xbox360", ns);
    env->add_namespace_alias("xb", ns);
  }
  {
    NamespacePtr ns = env->add_namespace("nunchuk");
  }
  {
    NamespacePtr ns = env->add_namespace("guitar");
  }
  {
    NamespacePtr ns = env->add_namespace("wiimote");
    env->add_namespace_alias("wii", ns);
  }
  {
    NamespacePtr ns = env->add_namespace("joystick");
    env->add_namespace_alias("js", ns);
    env->add_namespace_alias("joy", ns);
  }
  {
    NamespacePtr ns = env->add_namespace("hama-crux");
    env->add_namespace_alias("crux", ns);
    env->add_namespace_alias("zfang", ns);
  }
  {
    NamespacePtr ns = env->add_namespace("classic");
    env->add_namespace_alias("nintendo", ns);
    env->add_namespace_alias("snes", ns);
  }
  {
    NamespacePtr ns = env->add_namespace("gamepad");
    env->add_namespace_alias("gp", ns);
  }
  {
    NamespacePtr ns = env->lookup_namespace("playstation");
  }
  {
    NamespacePtr ns = env->lookup_namespace("evdev");
  }
  {
    NamespacePtr ns = env->lookup_namespace("xbox");
  }
  {
    NamespacePtr ns = env->lookup_namespace("nunchuk");
  }
  {
    NamespacePtr ns = env->lookup_namespace("guitar");
  }
  {
    NamespacePtr ns = env->lookup_namespace("wiimote");
  }
  {
    NamespacePtr ns = env->lookup_namespace("joystick");
  }
  {
    NamespacePtr ns = env->lookup_namespace("hama-crux");
  }
  {
    NamespacePtr ns = env->lookup_namespace("classic");
  }
  {
    NamespacePtr ns = env->lookup_namespace("gamepad");
  }
}

/* EOF */
