// Do not edit by hand, this file was automatically generated by ./gen_symbols.rb

#include "symbols/environment.hpp"
#include "symbols/namespace.hpp"
#include "symbols/symbol.hpp"

void init_environment_rel(EnvironmentPtr env)
{
  {
    NamespacePtr ns = env->add_namespace("playstation");
  }
  {
    NamespacePtr ns = env->add_namespace("xbox");
  }
  {
    NamespacePtr ns = env->add_namespace("nunchuk");
  }
  {
    NamespacePtr ns = env->add_namespace("guitar");
  }
  {
    NamespacePtr ns = env->add_namespace("wiimote");
  }
  {
    NamespacePtr ns = env->add_namespace("joystick");
  }
  {
    NamespacePtr ns = env->add_namespace("hama-crux");
  }
  {
    NamespacePtr ns = env->add_namespace("classic");
  }
  {
    NamespacePtr ns = env->add_namespace("gamepad");
  }
  {
    NamespacePtr ns = env->lookup_namespace("playstation");
  }
  {
    NamespacePtr ns = env->lookup_namespace("xbox");
  }
  {
    NamespacePtr ns = env->lookup_namespace("nunchuk");
  }
  {
    NamespacePtr ns = env->lookup_namespace("guitar");
  }
  {
    NamespacePtr ns = env->lookup_namespace("wiimote");
  }
  {
    NamespacePtr ns = env->lookup_namespace("joystick");
  }
  {
    NamespacePtr ns = env->lookup_namespace("hama-crux");
  }
  {
    NamespacePtr ns = env->lookup_namespace("classic");
  }
  {
    NamespacePtr ns = env->lookup_namespace("gamepad");
  }
}

/* EOF */
