#!/bin/sh
# Define constants
c_one_stick=1
c_two_stick=2
c_one_driver_running=2
c_two_drivers_running=3

# Define functions
load_first_driver_and_emul(){
  # Check if driver is already running for one Stick
  if [ $1 -lt $c_one_driver_running ]
  then
    # Kill media center
    killall xbmc.bin
    # Start driver
    sudo /home/media/Sources/xboxdrv-linux-0.4.4/./xboxdrv --id 0 --buttonmap lt=tl,rt=tr --dpad-only --silent &
    # Wait a little to avoid two launches of Mame, which can happen if the usb_added script is rerun before the driver is loaded
    sleep 3
    # Start custom script for launching Mame
    exec "/home/media/Scripts/MamePKK" &
  fi
}

load_second_driver(){
  # If second driver not yet running, start it
  if [ $1 -lt $c_two_drivers_running ]
  then
    sudo /home/media/Sources/xboxdrv-linux-0.4.4/./xboxdrv --id 0 --buttonmap lt=tl,rt=tr --dpad-only --silent &
  fi
}

# Get number of Hori Sticks plugged in
v_nb_of_sticks=`lsusb -d 0f0d:000d | wc -l`
# Get number of drivers loaded
v_nb_of_drivers=`ps -C xboxdrv | wc -l`
if [ $v_nb_of_sticks -eq $c_one_stick ]
then
  load_first_driver_and_emul $v_nb_of_drivers
elif [ $v_nb_of_sticks -eq $c_two_stick ]
then
  load_second_driver $v_nb_of_drivers
fi

