# Xbox360 USB Gamepad Userspace Driver
# Copyright (C) 2018-2026 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

image: ubuntu:24.04

variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -qq update
  - apt-get -qq -y install
    g++
    cmake
    pkg-config
    libusb-1.0-0-dev
    libudev-dev
    libevdev-dev
    libx11-dev
    libglib2.0-dev
    python3
    # optional Wiimote:
    # libcwiid-dev libbluetooth-dev

.build_xboxdrv_template: &build_xboxdrv
  stage: build
  script:
    - mkdir -p build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . -j"$(nproc)"

gcc:
  <<: *build_xboxdrv

gcc_warnings:
  <<: *build_xboxdrv
  script:
    - mkdir -p build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DWARNINGS=ON -DWERROR=ON
    - cmake --build . -j"$(nproc)"
