.TH JSTEST 1
.SH NAME
jstest \- joystick test program
.SH SYNOPSIS
.B jstest
[--normal] [--old] [--event] [--nonblock] [--select] <device-name>
.SH DESCRIPTION
.B jstest
can be used to test all the features of the Linux
joystick API, including non-blocking and \fBselect\fP(2) access, as
well as version 0.x compatibility mode.
.PP
It is also intended to
serve as an example implementation for those who wish to learn
how to write their own joystick using applications.
.SH OPTIONS
.TP
.I \--normal
One-line mode showing immediate status.
.TP
.I \--old
Same as --normal, using 0.x interface.
.TP
.I \--event
Prints events as they come in.
.TP
.I \--nonblock
Same as --event, in nonblocking mode.
.TP
.I \--select
Same as --event, using \fBselect\fP(2) call.
.SH SEE ALSO
\fBjscal\fP(1), \fBinputattach\fP(1), \fBselect\fP(2).
