# -*- python -*-

env = Environment(CPPFLAGS=["-g", "-O2", "-Wall", "-std=c99"])
env.Program("jstest", ["jstest.c"])
env.Program("evtest", ["evtest.c"])
env.Program("usbcat", ["usbcat.cpp"], LIBS = ["usb"])

# EOF #
